services:
  glins:
    build:
      context: .
    image: glins:noetic
    working_dir: /catkin_ws
    stdin_open: true
    tty: true
    environment:
      ROS_MASTER_URI: http://localhost:11311
      ROS_HOSTNAME: localhost
      QT_X11_NO_MITSHM: "1"
    volumes:
      - ./glins:/catkin_ws/src/glins
      - ./rtklib:/catkin_ws/src/rtklib
      - ./数据:/data
      - ./docker/output:/output
    command: bash
