# RTKLIB options for local data in /home/ys/glins_ws/src/数据/gnss

pos1-posmode       =kinematic
pos1-frequency     =l1+l2+l5
pos1-soltype       =forward
pos1-elmask        =10
pos1-dynamics      =on
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-sateph        =brdc
pos1-navsys        =41

pos2-armode        =3
pos2-bdsarmode     =on
pos2-arfilter      =on
pos2-arthres       =3
pos2-maxage        =1
pos2-rejionno      =10
pos2-rejcode       =30
pos2-rejdop        =2

out-solformat      =xyz
out-outhead        =on
out-outopt         =on
out-outvel         =off
out-timesys        =gpst
out-timeform       =tow
out-timendec       =3
out-height         =ellipsoidal
out-outstat        =residual

ant2-postype       =rinexhead

inpstr1-path       =/home/ys/glins_ws/src/数据/gnss/rover.obs
inpstr2-path       =/home/ys/glins_ws/src/数据/gnss/base.obs
inpstr3-path       =/home/ys/glins_ws/src/数据/gnss/BRDM00DLR_S_20240290000_01D_MN.rnx
inpstr4-path       =
outstr1-path       =/home/ys/glins_ws/src/数据/gnss/rtklib.pos
